'use strict';

/**
 *
 * Config for the router
 */
angular.module('app').run(
  ['$rootScope','$state','$stateParams',
    function($rootScope,$state,$stateParams){
      $rootScope.$state = $state;
      $rootScope.$stateParams = $stateParams;
    }]).config(
  ['$stateProvider','$urlRouterProvider','JQ_CONFIG',
    function($stateProvider,$urlRouterProvider,JQ_CONFIG){

      $urlRouterProvider.otherwise('/console/index');
      $stateProvider.state('console',{
        abstract:true,
        url:'/console',
        templateUrl:'html/temp_console.html'
      }).state('console.index',{
        url:'/index',
        views:{
          '':{
            templateUrl:'html/temp_index.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_index_temp.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load(['js/controllers/supplier/supplier.js',
                'js/controllers/supplier/goods.js',
                'js/controllers/proxy/proxy.js',
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.supplier',{
        url:'/supplier',
        views:{
          '':{
            templateUrl:'html/supplier/supplier_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_supplier.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/supplier/supplier.js']);
            }]
        }
      }).state('console.supplier_auth',{
        url:'/supplier_auth/{uid}',
        views:{
          '':{
            templateUrl:'html/supplier/supplier_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_supplier.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/supplier/supplier.js']);
            }]
        }
      }).state('console.proxy_qualification_auth',{
        url:'/proxy_qualification_auth/:sid/:category',
        views:{
          '':{
            templateUrl:'html/proxy/proxy_qualification_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_proxy.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/proxy/proxy.js']);
            }]
        }
      }).state('console.supplier_qualification_auth',{
        url:'/qualification_auth/:uid/:category',
        views:{
          '':{
            templateUrl:'html/supplier/supplier_qualification_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_supplier.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/supplier/supplier.js']);
            }]
        }
      }).state('console.supplier_goods',{
        url:'/supplier_goods',
        views:{
          '':{
            templateUrl:'html/supplier/goods_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_supplier.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/supplier/goods.js']);
            }]
        }
      }).state('console.supplier_goods_auth',{
        url:'/supplier_goods_auth/{id}',
        views:{
          '':{
            templateUrl:'html/supplier/goods_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_supplier.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/supplier/goods.js']);
            }]
        }
      }).state('console.proxy',{
        url:'/proxy',
        views:{
          '':{
            templateUrl:'html/proxy/proxy_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_proxy.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/proxy/proxy.js']);
            }]
        }
      }).state('console.proxy_shop_auth',{
        url:'/proxy_shop_auth/{uid}',
        views:{
          '':{
            templateUrl:'html/proxy/proxy_shop_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_proxy.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/proxy/proxy.js']);
            }]
        }
      }).state('console.proxy_goods',{
        url:'/proxy_goods',
        views:{
          '':{
            templateUrl:'html/proxy/goods_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_proxy.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/proxy/goods.js']);
            }]
        }
      }).state('console.proxy_goods_auth',{
        url:'/proxy_goods_auth/{id}',
        views:{
          '':{
            templateUrl:'html/proxy/goods_auth.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_proxy.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/proxy/goods.js']);
            }]
        }
      }).state('console.order',{
        url:'/order/{type}',
        views:{
          '':{
            templateUrl:'html/order/order_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_index_temp.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/order/order.js']);
            }]
        }
      }).state('console.order_again',{
        url:'/order_again',
        views:{
          '':{
            templateUrl:'html/order/order_again.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_order.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/order/order.js']);
            }]
        }
      }).state('console.order_detail',{
        url:'/order/{orderId}',
        views:{
          '':{
            templateUrl:'html/order/order_detail.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_order.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/order/order.js']);
            }]
        }
      }).state(
        'console.order_refund',
        {
          url:'/order_refund/{orderId}/{itemId}',
          views:{
            '':{
              templateUrl:'html/order/refund.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_order.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load([
                  'angularFileUpload',
                  'js/controllers/order/order.js']);
              }]
          }
        }).state('console.account',{
        url:'/account',
        views:{
          '':{
            templateUrl:'html/account/survey.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.setNotificationNumber',{
        url:'/setNotificationNumber',
        views:{
          '':{
            templateUrl:'html/account/setNotificationNumber.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.transfers',{
        url:'/transfers',
        views:{
          '':{
            templateUrl:'html/account/transfers.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.applyWithdrawal',{
        url:'/applyWithdrawal',
        views:{
          '':{
            templateUrl:'html/account/applyWithdrawal.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state(
        'console.rechargeMoney',
        {
          url : '/rechargeMoney',
          views : {
            '' : {
              templateUrl : 'html/account/rechargeMoney.html'
            },
            'navMenu' : {
              templateUrl : 'html/blocks/nav_order.html'
            }
          },
          resolve : {
            deps : [
              '$ocLazyLoad',
              function(
                $ocLazyLoad) {
                return $ocLazyLoad
                .load([

                  'js/controllers/account/account.js' ]);
              } ]
          }
        }).state('console.settingWithdrawal',{
        url:'/settingWithdrawal/{id}',
        views:{
          '':{
            templateUrl:'html/account/settingWithdrawal.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },
        resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.trading_list',{
        url:'/trading_list',
        views:{
          '':{
            templateUrl:'html/account/trading_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },
        resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.account_list',{
        url:'/account_list',
        views:{
          '':{
            templateUrl:'html/account/account_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.account_bill',{
        url:'/account_bill/{id}',
        views:{
          '':{
            templateUrl:'html/account/account_bill.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.account_withdrawcash',{
        url:'/account_withdrawcash',
        views:{
          '':{
            templateUrl:'html/account/withdrawcash.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_index_temp.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.income_detail',{
        url:'/income_detail',
        views:{
          '':{
            templateUrl:'html/account/income_detail.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },
        resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.withdrawals_record',{
        url:'/withdrawals_record',
        views:{
          '':{
            templateUrl:'html/account/withdrawals_record.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_account.html'
          }
        },
        resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([

                'js/controllers/account/account.js']);
            }]
        }
      }).state('console.marketing',{
        url:'/marketing',
        views:{
          '':{
            templateUrl:'html/marketing/agent_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/agent.js']);
            }]
        }
      }).state('console.agent',{
        url:'/agent',
        views:{
          '':{
            templateUrl:'html/marketing/agent_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/agent.js']);
            }]
        }
      }).state('console.activity',{
        url:'/activity',
        views:{
          '':{
            templateUrl:'html/marketing/activity_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/activity.js']);
            }]
        }
      }).state('console.activity_edit',{
        url:'/activity_edit/{id}',
        views:{
          '':{
            templateUrl:'html/marketing/activity_edits.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load(['angularFileUpload',
                'js/controllers/marketing/activity.js']);
            }]
        }
      }).state('console.activity_awards',{
        url:'/activity_awards/{id}/{cycle}',
        views:{
          '':{
            templateUrl:'html/marketing/activity_awards.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/activity.js']);
            }]
        }
      }).state('console.activity_participation_list',{
        url:'/activity_participation_list/{id}',
        views:{
          '':{
            templateUrl:'html/marketing/activity_participation_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/activity.js']);
            }]
        }
      }).state('console.ap_recommend_list',{
        url:'/ap_recommend_list/{aid}/{uid}',
        views:{
          '':{
            templateUrl:'html/marketing/activity_participation_recommend_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_marketing.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/marketing/activity.js']);
            }]
        }
      }).state('console.statistics',{
        url:'/statistics',
        views:{
          '':{
            templateUrl:'html/statistics/supplier_statistics.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_statistics.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/statistics/statistics.js']);
            }]
        }
      }).state('console.config',{
        url:'/config/{type}',
        views:{
          '':{
            templateUrl:'html/system/config_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_system.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/system/config.js']);
            }]
        }
      }).state('console.config_edit',{
        url:'/config_edit/{type}/{id}',
        views:{
          '':{
            templateUrl:'html/system/config_edit.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_system.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/system/config.js']);
            }]
        }
      }).state('console.help_category',{
        url:'/help',
        views:{
          '':{
            templateUrl:'html/help/category_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/help/category.js']);
            }]
        }
      })
      .state('console.help_create_category',{
        url:'/help_create/{id}',
        views:{
          '':{
            templateUrl:'html/help/create_category.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'angularBootstrapNavTree',
                'js/controllers/help/category.js']);
            }]
        }
      })
      .state('console.help_doc',{
        url:'/help_doc',
        views:{
          '':{
            templateUrl:'html/help/document_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/help/document.js']);
            }]
        }
      })
      .state('console.help_doc_edit',{
        url:'/help_doc_edit/{id}',
        views:{
          '':{
            templateUrl:'html/help/document_edit.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load(
                [
                  'angularFileUpload',
                  'ui.select'])
              .then(
                function(){
                  return $ocLazyLoad
                  .load([
                    'js/controllers/select.js',
                    'js/controllers/help/document.js',
                    'js/showcase/showcase.js']);
                });
            }]
        }
      })
      .state('console.help_question',{
        url:'/help_question',
        views:{
          '':{
            templateUrl:'html/help/question_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'angularFileUpload',
                'js/controllers/help/question.js']);
            }]
        }
      })
      .state('console.help_question_edit',{
        url:'/help_question_edit/{id}',
        views:{
          '':{
            templateUrl:'html/help/question_edit.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load(
                ['angularFileUpload','ui.select'])
              .then(
                function(){
                  return $ocLazyLoad
                  .load(['js/controllers/select.js','js/controllers/help/question.js']);
                });
            }]
        }
      })
      .state('console.help_keywords',{
        url:'/help_keywords',
        views:{
          '':{
            templateUrl:'html/help/keywords_list.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load([
                'js/controllers/help/keywords.js']);
            }]
        }
      })
      .state('console.help_keywords_edit',{
        url:'/help_keywords_edit/{id}',
        views:{
          '':{
            templateUrl:'html/help/keywords_edit.html'
          },
          'navMenu':{
            templateUrl:'html/blocks/nav_help.html'
          }
        },resolve:{
          deps:[
            '$ocLazyLoad',
            function($ocLazyLoad){
              return $ocLazyLoad
              .load(
                ['ui.select'])
              .then(
                function(){
                  return $ocLazyLoad
                  .load([
                    'js/controllers/select.js',
                    'js/controllers/help/keywords.js']);
                });
            }]
        }
      })
      .state(
        'console.ump_coupon_list',
        {
          url:'/ump_coupon_list',
          views:{
            '':{
              templateUrl:'html/marketing/coupon_list.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(['js/controllers/marketing/coupon.js']);
              }]
          }
        })
      .state(
        'console.ump_coupon_edit',
        {
          url:'/ump_coupon_edit/{id}',
          views:{
            '':{
              templateUrl:'html/marketing/coupon_edit.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(
                  ['ui.select'])
                .then(
                  function(){
                    return $ocLazyLoad
                    .load(['js/controllers/marketing/coupon.js']);
                  });
              }]
          }
        })
      .state(
        'console.ump_couponlog_list',
        {
          url:'/ump_couponlog_list/:couponId/:status',
          views:{
            '':{
              templateUrl:'html/marketing/couponlog_list.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(['js/controllers/marketing/coupon.js']);
              }]
          }
        })
      .state(
        'console.ump_activityfullsubgive_list',
        {
          url:'/ump_activityfullsubgive_list',
          views:{
            '':{
              templateUrl:'html/marketing/activity_fullsubgive_list.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(['js/controllers/marketing/activity_fullsubgive.js']);
              }]
          }
        })
      .state(
        'console.ump_activityfullsubgive_edit',
        {
          url:'/ump_activityfullsubgive_edit/{id}',
          views:{
            '':{
              templateUrl:'html/marketing/activity_fullsubgive_edit.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(['js/controllers/marketing/activity_fullsubgive.js']);
              }]
          }
        })
      .state(
        'console.income',
        {
          url:'/income/{uid}/{nickname}',
          views:{
            '':{
              templateUrl:'html/account/income.html'
            },
            'navMenu':{
              templateUrl:'html/blocks/nav_marketing.html'
            }
          },
          resolve:{
            deps:[
              '$ocLazyLoad',
              function($ocLazyLoad){
                return $ocLazyLoad
                .load(['js/controllers/marketing/activity.js']);
              }]
          }
        })
    }]);
